---
last_check:
  etag: W/"6afaf80a6adbb01885485cb45da834d0"
  version: 1.8.2
  at: 1473668396
checked_completion: true
completion_version: 1.8.2
endpoints:
  https://api.travis-ci.org/:
    access_token: jCCLwYjBa2CDShLjaoPX6Q
  https://api.travis-ci.com/:
    access_token: MdD9qbeEgqLI5WrlcIbFRg
repos:
  bigpandaio/authena:
    endpoint: https://api.travis-ci.com/
